name: aurask
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  chewie: ^1.2.2
  confetti: ^0.6.0-nullsafety
  cool_alert: ^1.1.0
  dashed_circle: ^0.0.2
  dio: ^4.0.0
  dotted_border: ^2.0.0
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_dynamic_links: ^2.0.7
  firebase_messaging: ^10.0.4
  flex_color_picker: ^2.1.2
  flutter_automation: ^2.0.0
  flutter_fortune_wheel: ^1.1.0
  flutter_local_notifications: ^6.0.0
  flutter_modular: ^3.3.1
  flutter_native_splash: ^1.2.0
  flutter_rating_bar: ^4.0.0
  flutter_redux: ^0.8.2
  flutter_spinkit: ^5.0.0
  font_awesome_flutter: ^9.1.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.0.5
  grouped_list: ^4.1.0
  html_unescape: ^2.0.0
  in_app_update: ^2.0.0
  intl: ^0.17.0
  path_provider: ^2.0.2
  paytm: ^3.0.0
  permission_handler: ^8.1.4+1
  provider: ^5.0.0
  rating_dialog: ^2.0.1
  redux: ^5.0.0
  settings_ui: ^1.0.0
  share_plus: ^2.1.4
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  story: ^0.5.1
  url_launcher: ^6.0.9
  video_player: ^2.1.12
  webview_flutter: ^2.0.10
  whatsapp_unilink: ^2.0.0
  youtube_player_iframe: ^2.1.0
  in_app_review: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/login/
    - assets/companies/
